### ISSUE TITLE
[Sequences] continue with another sequence

### ISSUE THREAD

**Issue by rhwy** [GhostWording/gw-config-apis#11]
We want to be able to link a sequence with another one.

In the same way that we execute actually a sequence element and then continue the execution of the tree with the next sequence element located in the **LinksTo** property, we want to continue with a sequence located in a pool of sequences defined later in another place (it can be sequencesFragments.json file or a share Api)

In order to choose the right fragment, we set some properties that will help the client (or the server if we call an api to serve the fragment) to choose the right fragment.

the first properties to support are the following:

* FragmentPath (string) : an Id of a specific sequence (or a path to a specific element within a sequence in the form sequenceId/idchildren1/idchildren2)
* Tags (string) : a string with a comma separated list of tags we want to match to choose the fragment.
 
```json
{
    "Type": "Node",
    "Id": "WouldYouLikeToFeelZen",
    
    "LinksToFragment": {
         "FragmentPath":"idOfMySequence"
    }
}
```

or 

```json
{
    "Type": "Node",
    "Id": "WouldYouLikeToFeelZen",
    
    "LinksToTag": {
        "Tags":"jokes, fun"
    }
}
```

**note** : These properties should all be matched, so, don't use mutually exclusive properties (if you specify a sequence id you should specify tags and vice-versa)

Behavior when you filter by : 

* "FragmentPath": it contains the id/path of a sequence element defined in the future SequenceFragments.json, it will load and execute that sequence as normal and when it'll be finished it will continue with the next sequence in the master file as normal
* "Tags": it will contain a list of tag names. we'll search in the SequenceFragments.json for sequences that maches these tags (from their Tag property see https://github.com/GhostWording/gw-config-apis/issues/10), pick one randomly if there is more that one sequence matching the tag, load and execute it and then continue with the next sequence in master file.

**Comment by andreasdieryck** [comment]
@rhwy 

Thank you for introducing the "tags" notion here. I am currently looking into implementing it with the guys. I would like to have your input on something.

In the issue #10, you suggested that we add tags in a sequence as per the following example, at the upper-level of a sequence:

```
{
    "Type": "Node",
    "Id": "MySequence",
    "Tags": ["joke","story","detectives"]
    ...
}
```
#### 1. Current suggestion for calling a file with a given Tag
If I want to call for a sequence that contains the `"Tags"` `joke"`, you suggest that we should use the following property/values:
```
{
    "Type": "Node",
    "Id": "MySequence2",
     ...
    "LinksToTag": {
        "Tags": "jokes, fun"
    }
```

#### 2. New suggestion for calling a file with a given Tag
However, it would perhaps make more sense if we included the Tag into an array, as we do when we attribute the tag. This way, we can call for many tags at the same time, as follows:
```
{
    "Type": "Node",
    "Id": "MySequence2",
     ...
    "LinksToTag": {
        "Tags": ["jokes", "fun"]
    }
```

A discussion will be necessary on the rules to apply when we call several tags. At the moment, we will try applying one. 
What do you think about this tiny change @rhwy ?

**Comment by rhwy** [comment]
sorry, I didn't come back to this issue when I implemented it.
so, yes, it's the **second option the good one**, the first was only a hypothesis in case it could simplify things on mobile side.
