### ISSUE TITLE
[conversation] reply to something written by the user

### ISSUE THREAD

**Issue by rhwy** [GhostWording/gw-config-apis#13]
when a user write something instead of clicking on quick-links, we decide to use the following behaviour:

* do a full-text search on texts api (all texts)
* if some text found:
   * get the prototype of the text and it's intention,
   * take a random image among the best images for the intention
   * create a card and show it to the user
* if not:
   * show a text (i didn't get that) + random owl
* continue with next sequence

**Comment by andreasdieryck** [comment]
@rhwy 
Ok - except for the owl. We don't a specific category of owl images on the database. So, if you don't mind, I'll just send flowers to our users 🌷. Does that sound good to you?

**Comment by rhwy** [comment]
I used Owl because it was supposed to be just like Quoteo, I just though owls are universal ;-)

if you want flowers, create a json with a set of urls of flowers images that I can pick to show to users

**Comment by andreasdieryck** [comment]
@rhwy 
As @Frederikos pointed out, the text-search API always returns something, regardless the input. Why is it different on your side?

**Comment by rhwy** [comment]
for quoteo we're limited to quotes not all texts, that makes a big difference.

just to verify and confirm behaviour, what api are you using @Frederikos ?

**Comment by andreasdieryck** [comment]
This one: http://api.cvd.io/bot/stickers/talktobot/?command=cardset&top=10&query=hola

**Comment by rhwy** [comment]
done
