### ISSUE TITLE
Time in SurveyPony Messenger 

### ISSUE THREAD

**Issue by andreasdieryck** [GhostWording/gw-config-apis#24]
We have noticed two abnormal behaviours in Survey SurveyPony recently

#### Issue 1: slow at the start

Since the middle of last week, 
- it takes anywhere from 2 minutes to 7 minutes for Survey Pony to reply to "Get Started" with "Welcome"
- all new users are affected, no exception
- before the middle of last week (at least until the 13th Feb), it seemed to reply instantly

There is also some delay between the "Welcome" and the second message, but it is usually much less than between "Get started" and "Welcome"

#### Issue 2: notification + message

The normal behaviour with regards to notifications is the following:
- we send a message (text / text + image) from the database at some point in the morning
- then we send a survey question, from wherever we last stopped in the masterfile

It seems that in reality:
- when we send a notification message of a card (text + image), we indeed send a survey question just after
- when we send a notification message made of text only, we don't send any survey question after, leaving the user without quick replies to interact with

Happy to help you if necessary :)

**Comment by rhwy** [comment]
that sounds like something falls in error and stop when there is no image available. I'll look at it

**Comment by rhwy** [comment]
1. I already identified the first on my side, it was a regression after last week's update, something I forgot in a refactoring, it's fixed on dev
