### ISSUE TITLE
API bot reload issues

### ISSUE THREAD

**Issue by vnguyendon** [GhostWording/gw-config-apis#31]
It seems that we are unable to apply any change but fragment content change to the API bots.
Please find below a list of the tests we ran to assess this issue.

1.Master Config Reload 
 When we modify the file data/bot/apps/botapis/masterSequencesConfiguration.json, use the reload command http://gw-bot-apis.azurewebsites.net/admin/sequences/masterconfiguration/reload?adminkey=61fd4333-61b1-4236-83c6-33bda5a9d6e6  and then the display command http://gw-bot-apis.azurewebsites.net/admin/sequences/masterconfiguration/show?adminkey=61fd4333-61b1-4236-83c6-33bda5a9d6e6, we do not see the change. The new bot declared in the master configuration does not seem to exist as command http://gw-bot-apis.azurewebsites.net/admin/sequences/reload/iostestbot?adminkey=61fd4333-61b1-4236-83c6-33bda5a9d6e6 results in "iostestbot configuration not found".

2. Sequences Order Reload
When we modify the sequences order in data/bot/apps/fortnite/fortniteMasterSequence.json and use the reload command http://gw-bot-apis.azurewebsites.net/admin/sequences/reload/fortnite?adminkey=61fd4333-61b1-4236-83c6-33bda5a9d6e6, the change is not taken into account (tested both within the eliteEmoji app and through the command http://gw-bot-apis.azurewebsites.net/api/sequences/next)

3. Sequences Content Reload
When we modify the first sequence content in data/bot/apps/fortnite/fortniteMasterSequence.json and use the reload command http://gw-bot-apis.azurewebsites.net/admin/sequences/reload/fortnite?adminkey=61fd4333-61b1-4236-83c6-33bda5a9d6e6, the change is not taken into account (tested both within the eliteEmoji app and through the command http://gw-bot-apis.azurewebsites.net/api/sequences/next)

--> Both (2. Sequences Order Reload) and (3. Sequences Content Reload) works fine when testing for the messenger bot, using the command http://gw-bot-fortnitebot.azurewebsites.net/admin/sequences/reload?adminkey=61fd4333-61b1-4236-83c6-33bda5a9d6e6

**Comment by rhwy** [comment]
point 4 is unrelated -> https://github.com/GhostWording/gw-config-apis/issues/33

**Comment by rhwy** [comment]
from what I could test most reload stuff works fine BUT you need to take in account that you need at least 10min between the moment you change a json file and the moment you call a reload api !

I can't do much more from now, could you please retry all your points after being sure that the files you changed are available and updated on the azure mirror of this repo we use to read the config files from the apis ? (on https://gw-config-api.azurewebsites.net for ex https://gw-config-api.azurewebsites.net/data/bot/apps/botapis/keywords-default.json)

**Comment by vnguyendon** [comment]
I tried points 1, 2 and 3 again and it does not work for me, though I waited a really long time (more than an hour).

**Comment by rhwy** [comment]
new version of botapi deployed with fixes for your points,  please re-test ;)

**Comment by vnguyendon** [comment]
Points 1, 2 and 3 are working now thanks !
