### ISSUE TITLE
"Lost" Fragments

### ISSUE THREAD

**Issue by vnguyendon** [GhostWording/gw-config-apis#32]
Some fragments that we use are not in data/bot/sequences/fragments/FragmentsMain04.json
At least we found one example, but they must be more :
The fragment called by keywors "dogs" seems to be data/bot/sequences/experiments/rui/OneFragmentForKeywordCat.json 
As it is not in FragmentsMain04.json it cannot be modified nor deleted with the usual commands.

**Comment by rhwy** [comment]
you just need to add missing fragments in main fragments file if you need to use them (actually FragmentsMain04.json)

note : in the the exemple you took, it was a test case, you don't need to check the coherence of these files it's not supposed to be used in production. But you're right on the point that fragments referenced by keywords file must be present in fragments main for working.
