### ISSUE TITLE
[botapis] keyword search error and reload

### ISSUE THREAD

**Issue by rhwy** [GhostWording/gw-config-apis#33]
4. Keywords Reload 
When we modify the file data/bot/apps/botapis/keywords-default.json and use the command http://gw-bot-apis.azurewebsites.net/admin/keywords/reload?adminkey=61fd4333-61b1-4236-83c6-33bda5a9d6e6 to reload, it does not seem to work : 
We changed 
>     {
>         "words" : ["dogs"],
>         "matchingType":"exact",
>         "fragment" : {
>             "tags" : ["cats"]
>         }
>     }
into
>     {
>         "words" : ["dogs","dog"],
>         "matchingType":"exact",
>         "fragment" : {
>             "tags" : ["cats"]
>         }
>     }
but when using the command http://gw-bot-apis.azurewebsites.net/api/sequences/keywordsearch with body {"Text": "dog"} we get the error 
> {
>     "TypeId": 4,
>     "Type": "InternalErrorForThisQuery",
>     "Message": "Object reference not set to an instance of an object."
> }

**Comment by rhwy** [comment]
1. the error is shown because keyword was not found (and this is because of a reload error or not waiting enough for the files to sync on gw-config-apis.azurewebsites.net)
2. the error message is not correct, it should be "Keyword not found" -> this has to be fixed

**Comment by rhwy** [comment]
appart the wrong error message, the reload works well 

-> BUT you should wait at least 10min between the update of keywords file and keywords reload!

**Comment by vnguyendon** [comment]
Indeed the reload works fine now
