### ISSUE TITLE
Messenger bots and fragments

### ISSUE THREAD

**Issue by vnguyendon** [GhostWording/gw-config-apis#37]
We have identified a systematic issue while using fragments in messenger bots : the fragment sequence stops immediately after the second quick reply. Please see the detailed test below : 

1. We tried to use the messenger bot "Museum Story Bot Demo" (ex British Museum Bot), where a new logic is being used : after a first introduction sequence, we see 4 times a "Choose your story" sequence.
2. The "Choose your Story" sequence is expected to display a clickable carrousel, with different choices of artwork. When we click on one, the bot is supposed to call the corresponding fragment and display the fragment sequence.
3. When we test it, we can see that the bot indeed starts to display the correct sequence, except that it does not go through it entirely. To be more precise, we noticed that the sequence stops immediately after the user choose a click reply for the second time in the fragment sequence.

Notes : 
- The same issue happens for all four choices from the carrousel.
- The same issue happens when we call a fragment "normally" (not after a clickable carrousel choice)
- The sequences used in the tested fragments work fine when called as a normal sequence in the master file (when not called as a fragment)
- The fragments seem to work fine in APIs bot (we tested it through the EliteEmoji app on iOS).

**Comment by OlivierBourdin** [comment]
Hey, that looks nicely explained to me
What do you think @rhwy ?

**Comment by rhwy** [comment]
this sounds like a bug or corner case. 
I'll look into it but first I'll have to test the messenger bots with the new get next sequence mechanism
I'll put it in my todo for august

**Comment by rhwy** [comment]
is that the right master file you used in your exemple ? https://github.com/GhostWording/gw-config-apis/blob/master/data/bot/apps/museumapps/britishmuseum/britishmuseumMasterSequence.json

**Comment by vnguyendon** [comment]
This one was used for the APIs bot. The masterfile linked to the messenger bot is https://github.com/GhostWording/gw-config-apis/blob/master/data/bot/apps/britishmuseumbot/britishmuseumbotMaster.json
But they are the same for now.
