### ISSUE TITLE
Ghost bots

### ISSUE THREAD

**Issue by vnguyendon** [GhostWording/gw-config-apis#38]
Some bots from botapis behave as if they had no sequence do show, although it does. The bots in this situation are : `onboardingandroid`, `unittestbot`, `louisgscreenbot`, `ineedhugsandroid`, `savethekitten`, `kittentile`, `onboardingprocess`.

Let's take botname "onboardingandroid" as an example.

I tried to call the "Sequence Next" api via `http://gw-bot-apis.azurewebsites.net/api/sequences/next`. Body : 
> {
	"Botname": "onboardingandroid",
	"DeviceId": "",
	"FacebookId": "test",
	"LastSequenceId": ""
}

I cleared the Id history beforehand with `http://gw-bot-apis.azurewebsites.net/admin/command/history/clear?botName=onboardingandroid&deviceId=&facebookId=test&adminkey=61fd4333-61b1-4236-83c6-33bda5a9d6e6`.

I was expecting to receive the first sequence. When call  `http://gw-bot-apis.azurewebsites.net/admin/sequences/masterconfiguration/show?adminkey=61fd4333-61b1-4236-83c6-33bda5a9d6e6`, we see 
> {
            "Name": "onboardingandroid",
            "File": "/data/bot/apps/onboarding/onboardingbotAndroidMasterfile.json",
            "Source": null
}

and in `/data/bot/apps/onboarding/onboardingbotAndroidMasterfile.json`, we see 

> {
  "GroupName": "onboarding",
  "SequenceFiles": [
    { "order" : 10, "file":["/data/bot/sequences/appspecials/onboardingbot/OnboardingHello.json"]},
    { "order" : 20, "file":["/data/bot/sequences/appspecials/onboardingbot/MoreAboutAppRedirect.json"]},
    . . .
  ]
}

Thus I would be expecting the "Sequence Next" api to show the sequence `/data/bot/sequences/appspecials/onboardingbot/OnboardingHello.json`

Instead, I received : 
> {
    "TypeId": 1,
    "Type": "NoMoreSequencesAvailable",
    "Message": "There is no more valid sequences available for test-onboardingandroid"
}

**Comment by vnguyendon** [comment]
Andreas also tried with completely new Id

**Comment by rhwy** [comment]
I found a bug introduced by previous change that only saves files when they are new or modified. 
it's fixed in production, you should try again now

**Comment by vnguyendon** [comment]
It works fine now thanks
